name: Build and Deploy LaTeX Resume (TinyTeX)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TinyTeX (Minimal LaTeX)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO- "https://yihui.org/tinytex/install-unx.sh" | sh
          echo "::add-path::${HOME}/bin"

      - name: Compile LaTeX
        run: |
          mkdir -p output
          ~/.TinyTeX/bin/*/pdflatex -interaction=nonstopmode -output-directory=output resume.tex

      - name: Copy PDF to root for deploy
        run: cp output/resume.pdf .

      - name: Deploy PDF to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./
