name: Build and Deploy LaTeX Resume

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile LaTeX using latex-action
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex

      - name: Rename and copy PDF to gh-pages folder
        run: |
          mkdir public
          mv resume.pdf public/Resume_Tejas_Athalye.pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
